### ISSUE TITLE
errors and warnings bundling MongoDB and Mongoose

### ISSUE THREAD

**Issue by ryanchristo** [ryanchristo/fcc-nightlife-app#1]
After bundling server-side code targeted for node, I receive the following errors and warnings:

```
WARNING in ./~/mongodb/~/es6-promise/dist/es6-promise.js
    Module not found: Error: Can't resolve 'vertx' in '/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/node_modules/mongodb/node_modules/es6-promise/dist'
     @ ./~/mongodb/~/es6-promise/dist/es6-promise.js 134:18-28
     @ ./~/mongodb/lib/mongo_client.js
     @ ./~/mongodb/index.js
     @ ./~/mongoose/lib/index.js
     @ ./~/mongoose/index.js
     @ ./server/database.js
     @ ./server/server.js
    
    WARNING in ./~/express/lib/view.js
    76:29-56 Critical dependency: the request of a dependency is an expression
    
    WARNING in ./~/mongoose/lib/drivers/index.js
    10:11-74 Critical dependency: the request of a dependency is an expression
    
    WARNING in ./~/require_optional/index.js
    65:18-42 Critical dependency: the request of a dependency is an expression
    
    WARNING in ./~/require_optional/index.js
    73:20-44 Critical dependency: the request of a dependency is an expression
    
    WARNING in ./~/require_optional/index.js
    80:35-67 Critical dependency: the request of a dependency is an expression
```

After attempting to run the code, I receive the following error:

```
var r;r="undefined"==typeof window?!function(){var e=new Error('Cannot find module "."');throw e.code="MODULE_NOT_FOUND",e}():n(662),/*!

Error: Cannot find module "."
    at /Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:370:54
    at Object.<anonymous> (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:370:124)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.<anonymous> (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:310:541)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.x (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1212:7)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.a (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:777:29755)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.i../collection (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:931:18)
```

I have my server-side configuration for webpack setup as follows :

```
const serverConfig = {
  target: 'node',
  entry: {
    main: './server/server.js'
  },
  output: {
    filename: 'server.min.js',
    path: 'build'
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: [
          {
            loader: 'babel-loader',
            query: 'presets[]=latest,presets[]=react,presets[]=stage-2'
          }
        ]
      },
      {
        test: /\.json$/,
        use: [
          {
            loader: 'json-loader'
          }
        ]
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.json', '.jsx']
  }
}
```

**Comment by ryanchristo** [comment]
The error is being caused by /node_modules/mongoose/lib/drivers/index.js, which references a window object that is not recognized in a node environment.

```
/*!
 * ignore
 */

var driver;

if (typeof window === 'undefined') {
  driver = require(global.MONGOOSE_DRIVER_PATH || './node-mongodb-native');
} else {
  driver = require('./browser');
}

/*!
 * ignore
 */

module.exports = driver;
```

**Comment by ryanchristo** [comment]
The error is being caused by a module that cannot be located when running the code in /node_modules/mongoose/lib/drivers/index.js.

```
/*!
 * ignore
 */

var driver;

if (typeof window === 'undefined') {
  driver = require(global.MONGOOSE_DRIVER_PATH || './node-mongodb-native');
} else {
  driver = require('./browser');
}

/*!
 * ignore
 */

module.exports = driver;
```

**Comment by ryanchristo** [comment]
I attempted to default to the browser by editing the code as follows:

```
/*!
 * ignore
 */

var driver = require('./browser');

/*!
 * ignore
 */

module.exports = driver;
```

I bundled and ran the code and received the following error:

```
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '//../package.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.<anonymous> (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1566:11082)
    at Object.<anonymous> (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1566:11135)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.<anonymous> (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1566:9121)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.<anonymous> (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:802:696)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.<anonymous> (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1118:7)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at r (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1622:15285)
    at Object.x (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1218:76)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
    at Object.a (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:777:29755)
    at t (/Users/Admin/Workspace/projects/fcc-projects/fcc-nightlife-app/build/server.min.js:1:163)
```

**Comment by ryanchristo** [comment]
I installed webpack-node-externals and invoked the function in externals:

```
const nodeExternals = require('webpack-node-externals')

...

const serverConfig = {
  target: 'node',
  entry: {
    main: './server/server.js'
  },
  output: {
    filename: 'server.min.js',
    path: 'build'
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: [
          {
            loader: 'babel-loader',
            query: 'presets[]=latest,presets[]=react,presets[]=stage-2'
          }
        ]
      },
      {
        test: /\.json$/,
        use: [
          {
            loader: 'json-loader'
          }
        ]
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.json', '.jsx']
  },
  externals: [nodeExternals()]
}
```

I no longer receive any errors or warnings when running the bundled code on a local environment. I deployed the code to heroku and ran the bundled server on heroku and received no errors.

closing issue
